import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],

  darkMode: 'class',
  theme: {
    extend: {
      backgroundImage: {
        'dice-canvas': 'linear-gradient(135deg, #1a1a1a 0%, #0a0a0a 100%)',
      },
      colors: {
        // DNDB Dark Theme (default)
        'dndb': {
          'surface': '#0f172a',
          'surface-secondary': '#1e293b',
          'surface-tertiary': '#334155',
          'surface-quaternary': '#475569',
          'card': '#1e293b',
          'card-secondary': '#334155',
          'card-tertiary': '#475569',
          'text-primary': '#f8fafc',
          'text-secondary': '#cbd5e1',
          'text-tertiary': '#94a3b8',
          'text-quaternary': '#64748b',
          'text-muted': '#475569',
          'primary': '#dc2626',
          'primary-hover': '#b91c1c',
          'accent': '#3b82f6',
          'accent-hover': '#2563eb',
          'accent-text': '#ffffff',
          'accent-bg': '#1e40af',
          'accent-border': '#3b82f6',
          'button': '#dc2626',
          'button-hover': '#b91c1c',
          'button-text': '#ffffff',
          'success': '#10b981',
          'success-text': '#ffffff',
          'success-hover': '#059669',
          'success-bg': '#064e3b',
          'success-border': '#10b981',
          'warning': '#f59e0b',
          'warning-text': '#ffffff',
          'warning-bg': '#451a03',
          'warning-border': '#f59e0b',
          'error': '#ef4444',
          'error-text': '#ffffff',
          'error-hover': '#dc2626',
          'error-bg': '#7f1d1d',
          'error-border': '#ef4444',
          'border': '#475569',
          'border-light': '#64748b',
          'overlay': 'rgba(0, 0, 0, 0.5)',
          'error-text-light': '#fca5a5',
          'dice-default': '#dc2626',
          'dice-canvas-bg': '#1a1a1a',
        },
        // DNDB Light Theme
        'dndb-light': {
          'surface': '#fef3c7',
          'surface-secondary': '#fde68a',
          'surface-tertiary': '#fcd34d',
          'surface-quaternary': '#fbbf24',
          'card': '#fde68a',
          'card-secondary': '#fcd34d',
          'card-tertiary': '#fbbf24',
          'text-primary': '#92400e',
          'text-secondary': '#a16207',
          'text-tertiary': '#d97706',
          'text-quaternary': '#f59e0b',
          'text-muted': '#fbbf24',
          'primary': '#dc2626',
          'primary-hover': '#b91c1c',
          'accent': '#3b82f6',
          'accent-hover': '#2563eb',
          'accent-text': '#ffffff',
          'accent-bg': '#1e40af',
          'accent-border': '#3b82f6',
          'button': '#dc2626',
          'button-hover': '#b91c1c',
          'button-text': '#ffffff',
          'success': '#059669',
          'success-text': '#ffffff',
          'success-hover': '#047857',
          'success-bg': '#064e3b',
          'success-border': '#059669',
          'warning': '#d97706',
          'warning-text': '#ffffff',
          'warning-bg': '#451a03',
          'warning-border': '#d97706',
          'error': '#dc2626',
          'error-text': '#ffffff',
          'error-hover': '#b91c1c',
          'error-bg': '#7f1d1d',
          'error-border': '#dc2626',
          'border': '#fbbf24',
          'border-light': '#f59e0b',
          'overlay': 'rgba(0, 0, 0, 0.3)',
          'error-text-light': '#dc2626',
          'dice-default': '#dc2626',
          'dice-canvas-bg': '#fef3c7',
        },
        // Enchanted Forest Theme
        'enchanted': {
          'surface': '#064e3b',
          'surface-secondary': '#065f46',
          'surface-tertiary': '#047857',
          'surface-quaternary': '#059669',
          'card': '#065f46',
          'card-secondary': '#047857',
          'card-tertiary': '#059669',
          'text-primary': '#d1fae5',
          'text-secondary': '#a7f3d0',
          'text-tertiary': '#6ee7b7',
          'text-quaternary': '#34d399',
          'text-muted': '#10b981',
          'primary': '#10b981',
          'primary-hover': '#059669',
          'accent': '#8b5cf6',
          'accent-hover': '#7c3aed',
          'accent-text': '#ffffff',
          'accent-bg': '#5b21b6',
          'accent-border': '#8b5cf6',
          'button': '#10b981',
          'button-hover': '#059669',
          'button-text': '#ffffff',
          'success': '#10b981',
          'success-text': '#ffffff',
          'success-hover': '#059669',
          'success-bg': '#064e3b',
          'success-border': '#10b981',
          'warning': '#f59e0b',
          'warning-text': '#ffffff',
          'warning-bg': '#451a03',
          'warning-border': '#f59e0b',
          'error': '#ef4444',
          'error-text': '#ffffff',
          'error-hover': '#dc2626',
          'error-bg': '#7f1d1d',
          'error-border': '#ef4444',
          'border': '#047857',
          'border-light': '#059669',
          'overlay': 'rgba(0, 0, 0, 0.5)',
          'error-text-light': '#fca5a5',
          'dice-default': '#10b981',
          'dice-canvas-bg': '#064e3b',
        },
        // Dungeon Theme
        'dungeon': {
          'surface': '#1c1917',
          'surface-secondary': '#292524',
          'surface-tertiary': '#44403c',
          'surface-quaternary': '#57534e',
          'card': '#292524',
          'card-secondary': '#44403c',
          'card-tertiary': '#57534e',
          'text-primary': '#fafaf9',
          'text-secondary': '#e7e5e4',
          'text-tertiary': '#d6d3d1',
          'text-quaternary': '#a8a29e',
          'text-muted': '#78716c',
          'primary': '#dc2626',
          'primary-hover': '#b91c1c',
          'accent': '#f59e0b',
          'accent-hover': '#d97706',
          'accent-text': '#ffffff',
          'accent-bg': '#92400e',
          'accent-border': '#f59e0b',
          'button': '#dc2626',
          'button-hover': '#b91c1c',
          'button-text': '#ffffff',
          'success': '#10b981',
          'success-text': '#ffffff',
          'success-hover': '#059669',
          'success-bg': '#064e3b',
          'success-border': '#10b981',
          'warning': '#f59e0b',
          'warning-text': '#ffffff',
          'warning-bg': '#451a03',
          'warning-border': '#f59e0b',
          'error': '#ef4444',
          'error-text': '#ffffff',
          'error-hover': '#dc2626',
          'error-bg': '#7f1d1d',
          'error-border': '#ef4444',
          'border': '#57534e',
          'border-light': '#78716c',
          'overlay': 'rgba(0, 0, 0, 0.7)',
          'error-text-light': '#fca5a5',
          'dice-default': '#f59e0b',
          'dice-canvas-bg': '#1c1917',
        },
        // Nobility Theme
        'nobility': {
          'surface': '#1e1b4b',
          'surface-secondary': '#312e81',
          'surface-tertiary': '#4338ca',
          'surface-quaternary': '#6366f1',
          'card': '#312e81',
          'card-secondary': '#4338ca',
          'card-tertiary': '#6366f1',
          'text-primary': '#e0e7ff',
          'text-secondary': '#c7d2fe',
          'text-tertiary': '#a5b4fc',
          'text-quaternary': '#818cf8',
          'text-muted': '#6366f1',
          'primary': '#dc2626',
          'primary-hover': '#b91c1c',
          'accent': '#fbbf24',
          'accent-hover': '#f59e0b',
          'accent-text': '#ffffff',
          'accent-bg': '#92400e',
          'accent-border': '#fbbf24',
          'button': '#dc2626',
          'button-hover': '#b91c1c',
          'button-text': '#ffffff',
          'success': '#10b981',
          'success-text': '#ffffff',
          'success-hover': '#059669',
          'success-bg': '#064e3b',
          'success-border': '#10b981',
          'warning': '#f59e0b',
          'warning-text': '#ffffff',
          'warning-bg': '#451a03',
          'warning-border': '#f59e0b',
          'error': '#ef4444',
          'error-text': '#ffffff',
          'error-hover': '#dc2626',
          'error-bg': '#7f1d1d',
          'error-border': '#ef4444',
          'border': '#4338ca',
          'border-light': '#6366f1',
          'overlay': 'rgba(0, 0, 0, 0.6)',
          'error-text-light': '#fca5a5',
          'dice-default': '#fbbf24',
          'dice-canvas-bg': '#1e1b4b',
        },
      },
    },
  },
  plugins: [],
}

export default config 